/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import org.tetris.UIRouter;

import javafx.application.Application;
import javafx.stage.Stage;

public class App extends Application {
    @Override
    public void start(Stage stage) {
        UIRouter nav = new UIRouter(stage);
        nav.showStartMenu(); // 시작 화면 표시
        stage.show();
    }

    public static void main(String[] args) {
        launch();
    }
}